const priceDisplayCardData = [
  {
    id: "1",
    title: "AJMAN OFFSHORE",
    price: "2,997 ",
    description: "Ajman Offshore New Company formation includes",
    points: [
      "Attestation Charges",
      "Registered Agent",
      "Registered Office",
      "Varal Administrative",
      "Preparing Statutory File",
      "Liasing with Registration Authorities",
      "Due Diligence Appraisal",
      "Keeping The Register",
      "Seal Charges",
      "Certificate of Good Standing",
    ],
    path: "#",
  },
  {
    id: "2",
    title: "RAK ICC",
    price: "2,997 ",
    description: "Rak Icc New Company formation include",
    points: [
      "Attestation Charges",
      "Registered Agent",
      "Registered Office",
      "Varal Administrative",
      "Preparing Statutory File",
      "Liasing with Registration Authorities",
      "Due Diligence Appraisal",
      "Keeping The Register",
      "Seal Charges",
      "Certificate of Good Standing",
    ],
    path: "#",
  },
  {
    id: "3",
    title: "SHARJAH MEDIA CITY",
    price: "4,124",
    description: "Sharjah Media City New Company formation include",
    points: [
      "Attestation Charges",
      "Registered Agent",
      "Registered Office",
      "Varal Administrative",
      "Preparing Statutory File",
      "Liasing with Registration Authorities",
      "Due Diligence Appraisal",
      "Keeping The Register",
      "Seal Charges",
      "Certificate of Good Standing",
    ],
    path: "#",
  },
];

export default priceDisplayCardData;
